- name: Install apache2
  apt:
    pkg: 
    - apache2
    - php 
    - libapache2-mod-php
  

- name: Copy index.html
  copy:
    src: index_{{ ansible_hostname }}.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy sesion.php
  copy:
    src: sesion.php
    dest: /var/www/html/sesion.php
    owner: www-data
    group: www-data
    mode: 0644
  

