- name: Install haproxy
  apt:
    pkg: 
    - haproxy
    

- name: Config haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      This is the third line...
      This is the fifth line...
      This is the sixth line...
    
  

