- name: Install haproxy
  apt:
    pkg: 
    - haproxy
    

- name: Config haproxy.cfg
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      listen granja_cda 
      bind {{ansible_ssh_host}}:80 
      mode http
      stats enable
      stats auth  cda:cda
      balance roundrobin
      server apache1 {{hostvars['apache1']['ansible_eth1']['ipv4']['address']}}:80 maxconn 128 check
      server apache2 {{hostvars['apache2']['ansible_eth1']['ipv4']['address']}}:80 maxconn 128 check
  notify:
    restart haproxy  
    
  

